import Scott1980.Neighborhood.Proposition710
import Mathlib.Tactic

/-!
# Definition 7.11 (Scott 1981, PRG-19, §7) — finite-element joins in `ℙ𝒟`

Scott introduces the power-domain analogue of a *finite set* of elements.

**Definition 7.11.** For elements `x₀, …, x_{n-1} ∈ |𝒟|` define

`{x₀, …, x_{n-1}} = { z ∈ |ℙ𝒟| ∣ ∃ X₀ ∈ x₀ … ∃ X_{n-1} ∈ x_{n-1}.
  ⋃_{i<n} (↑X_i) ⊆ z }`,

where `↑X` is the principal filter of `X ∈ 𝒟`. Scott also notes the equivalent formulation
`∀ i < n. X_i ∈ z` (read with `X_i` identified with the down-set `↓X_i ∈ ℙ𝒟`).

On finite elements `↑X` of `|𝒟|`, `{↑X}` is the principal filter `↑(↓X)` of `ℙ𝒟` (Prop 7.12).

## What this file formalizes

Building on `Proposition710.lean`'s `PowerDomain`, we package Scott's join as a filter
`PDfinJoin xs : V.PowerDomain.Element` for `xs : Fin n → V.Element` (`n = 0` gives `⊥`).

Membership is the down-set form of Scott's union condition:

`W ∈ {x₀,…,x_{n-1}} ↔ ∃ (X_i ∈ x_i). PD.mem W ∧ ∀ i. ↓X_i ⊆ W`,

equivalently `PD.mem W ∧ ⋃_{i<n} ↓X_i ⊆ W` for some choice of representatives. The singleton
`PDsingleton x` is the unary join; on principal filters, `PDsingleton (↑X) = ↑(↓X)`.
-/

namespace Scott1980.Neighborhood

namespace NeighborhoodSystem

variable {α : Type*} (V : NeighborhoodSystem α)

/-! ### Definition 7.11 — membership predicate. -/

/-- **Definition 7.11 — membership.** A `ℙ𝒟`-neighbourhood `W` lies in the join of
`x₀, …, x_{n-1}` iff some choice of representatives `X_i ∈ x_i` has every down-set
`↓X_i` contained in `W` (Scott's `⋃_{i<n} (↑X_i) ⊆ z`, read as down-sets in `ℙ𝒟`). -/
def PDmemFinJoin {n : ℕ} (xs : Fin n → V.Element) (W : Set (Set α)) : Prop :=
  ∃ (X : Fin n → Set α) (hX : ∀ i, (xs i).mem (X i)),
    V.PowerDomain.mem W ∧ ∀ i, V.upSet (X i) ⊆ W

/-! ### Definition 7.11 — the join element. -/

/-- **Definition 7.11 — the empty join.** With no arguments, `{ } = ⊥` (the least element of
`|ℙ𝒟|`). -/
def PDfinJoinZero : V.PowerDomain.Element := V.PowerDomain.bot

/-- **Definition 7.11 — the non-empty join.** For `n ≥ 1`, `{x₀,…,x_{n-1}}` is the filter
generated by Scott's union condition. -/
def PDfinJoinSucc {m : ℕ} (xs : Fin (m + 1) → V.Element) : V.PowerDomain.Element where
  mem := V.PDmemFinJoin xs
  sub hW := by obtain ⟨_, _, hPD, _⟩ := hW; exact hPD
  master_mem := by
    refine ⟨fun i => V.master, fun i => (xs i).master_mem, V.PDmem_master, fun i Z hz => hz⟩
  inter_mem h1 h2 := by
    obtain ⟨X1, hX1, hPD1, hsub1⟩ := h1
    obtain ⟨X2, hX2, hPD2, hsub2⟩ := h2
    refine ⟨fun i => X1 i ∩ X2 i, fun i => (xs i).inter_mem (hX1 i) (hX2 i),
      V.PDmem_inter hPD1 hPD2, fun i Y hY => ?_⟩
    rw [← V.upSet_inter] at hY
    rcases hY with ⟨hY1, hY2⟩
    exact ⟨hsub1 i hY1, hsub2 i hY2⟩
  up_mem h hW hsub := by
    obtain ⟨X, hX, _, hsub'⟩ := h
    exact ⟨X, hX, hW, fun i => (hsub' i).trans hsub⟩

/-- **Definition 7.11.** The finite-element join `{x₀,…,x_{n-1}}` in `|ℙ𝒟|`. The empty
family yields `⊥`; otherwise use Scott's union-of-down-sets condition. -/
def PDfinJoin (n : ℕ) (xs : Fin n → V.Element) : V.PowerDomain.Element :=
  match n with
  | 0 => V.PDfinJoinZero
  | m + 1 => V.PDfinJoinSucc xs

@[simp] theorem PDmem_finJoinZero {W : Set (Set α)} :
    (V.PDfinJoinZero).mem W ↔ W = V.PowerDomain.master := by
  rw [PDfinJoinZero, mem_bot, PowerDomain_master]

theorem PDmem_finJoinSucc {m : ℕ} (xs : Fin (m + 1) → V.Element) {W : Set (Set α)} :
    (V.PDfinJoinSucc xs).mem W ↔ V.PDmemFinJoin xs W := Iff.rfl

theorem PDmem_finJoin {n : ℕ} (xs : Fin n → V.Element) {W : Set (Set α)} :
    (V.PDfinJoin n xs).mem W ↔
      if n = 0 then W = V.PowerDomain.master else V.PDmemFinJoin xs W := by
  match n with
  | 0 => simp [PDfinJoin, PDfinJoinZero, mem_bot, PowerDomain_master]
  | m + 1 => simp [PDfinJoin, PDfinJoinSucc, PDmem_finJoinSucc]

/-- **Definition 7.11 — Scott's displayed union form.** For `n ≥ 1`, membership is equivalent to
some representatives `X_i ∈ x_i` with `⋃_{i<n} ↓X_i ⊆ W`. -/
theorem PDmem_finJoin_iUnion {m : ℕ} (xs : Fin (m + 1) → V.Element) {W : Set (Set α)} :
    (V.PDfinJoinSucc xs).mem W ↔
      ∃ (X : Fin (m + 1) → Set α) (hX : ∀ i, (xs i).mem (X i)),
        V.PowerDomain.mem W ∧
          (⋃ i, V.upSet (X i)) ⊆ W := by
  rw [PDmem_finJoinSucc]
  constructor
  · rintro ⟨X, hX, hPD, hsub⟩
    exact ⟨X, hX, hPD, Set.iUnion_subset hsub⟩
  · rintro ⟨X, hX, hPD, hsub⟩
    exact ⟨X, hX, hPD, (Set.iUnion_subset_iff).mp hsub⟩

/-- **Definition 7.11 — singleton join.** Write `{x}` for the unary join. -/
def PDsingleton (x : V.Element) : V.PowerDomain.Element := V.PDfinJoin 1 (fun (_ : Fin 1) => x)

@[simp] theorem PDmem_singleton {x : V.Element} {W : Set (Set α)} :
    (V.PDsingleton x).mem W ↔
      ∃ X, x.mem X ∧ V.PowerDomain.mem W ∧ V.upSet X ⊆ W := by
  rw [PDsingleton, PDfinJoin, PDmem_finJoinSucc, PDmemFinJoin]
  constructor
  · rintro ⟨X, hX, hPD, hsub⟩
    exact ⟨X 0, hX 0, hPD, hsub 0⟩
  · rintro ⟨X, hX, hPD, hsub⟩
    refine ⟨fun _ => X, fun _ => hX, hPD, fun _ => hsub⟩

end NeighborhoodSystem

end Scott1980.Neighborhood
