import Scott1980.Neighborhood.Proposition710
import Scott1980.Neighborhood.Definition72

/-!
# Exercise 7.19 (Scott 1981, PRG-19, §7) — `D ↦ ℙD` is a functor

> **EXERCISE 7.19.** Prove that `D ↦ ℙD` is a functor by defining for each `f : D → E` a mapping
> `ℙf : ℙD → ℙE` by the formula
> `⋃_{i<n} ↓Xᵢ  ℙf  ⋃_{j<m} ↓Yⱼ   iff   ∀ i<n ∃ j<m. Xᵢ f Yⱼ`.
> Be sure to check that `ℙf` is approximable and that `ℙ` preserves identity maps and composition.
> If `f` is computable, is `ℙf`? Is there a combinator `λf. ℙf`? What is `ℙf({x, y}) = ??`

## The mapping `ℙf`

Scott's formula refers to a *representation* `A = ⋃_{i<n} ↓Xᵢ`, which is not unique. We give the
**representation-independent** relation

`(ℙf).rel A B  :=  A ∈ ℙD ∧ B ∈ ℙE ∧ ∀ X ∈ A, ∃ Y ∈ B, X f Y`   (`PFmap`),

and prove it agrees with Scott's display on any generators (`PFmap_rel_fin`): for finite lists
`L₁ ⊆ 𝒟`, `L₂ ⊆ ℰ`,

`(ℙf).rel (⋃_{X∈L₁} ↓X) (⋃_{Y∈L₂} ↓Y)  ↔  ∀ X ∈ L₁, ∃ Y ∈ L₂, X f Y`.

The two readings coincide because every member `X ∈ A` lies below a generator `Xᵢ` and `f` is
monotone (`mono`), and conversely each generator is itself a member. Approximability (`PFmap`) uses:
`master_rel` from `f.master_rel`; `inter_right` from `f.inter_right` together with the fact that the
power domain is *downward closed* (`PDmem_down`) so the witness `Y ∩ Y'` lands back in `B ∩ B'`;
`mono` is immediate (the body only quantifies over set membership).

## Functoriality

* `PFmap_idMap` — `ℙ(I_D) = I_{ℙD}` (the body `∀ X ∈ A, ∃ Y ∈ B, X ⊆ Y` collapses to `A ⊆ B` by
  downward closure).
* `PFmap_comp` — `ℙ(g ∘ f) = ℙg ∘ ℙf`. The non-trivial direction builds the intermediate
  `ℙE`-neighbourhood `B = ⋃_{Y∈M} ↓Y` from a list `M` of witnesses gathered along the generators of
  `A` by a **choice-free** list recursion (`comp_witness`: `obtain`-ing each existential witness in a
  `Prop` goal needs no choice).

## Discussion (Scott's three questions)

* **If `f` is computable, is `ℙf`?** *Yes* (`PFmap_isComputable` / `PFmap_isComputable_Ypd`). Over the
  canonical presentations of Proposition 7.10 (`PDPresentation`, codes = finite lists of `𝒟`-indices),
  the relation reduces (`PFmap_rel_Ypd_iff`) to
  `∀ a ∈ dl c, ∃ b ∈ dl d, Xₐ f Y_b`, a bounded `∀`/`∃` over the r.e. relation `Xₐ f Y_b`; r.e.-ness
  is preserved by bounded `∃` (`bExists_decodeList_re`) and bounded `∀` with a parameter
  (`REPred.forall_mem_decodeList₂`). So `ℙf` is computable whenever `f` is.
* **Is there a combinator `λf. ℙf`?** Yes in spirit: `ℙf` is monotone and continuous in `f`
  (`PFmap` only ever *uses* `f.rel` positively), so the operation `f ↦ ℙf` is itself an approximable
  map `(D → E) → (ℙD → ℙE)` — its full internalisation as a combinator is of the same flavour as the
  function-space combinators of Theorem 7.4 / Exercise 7.21 and is not pursued here.
* **What is `ℙf({x, y})`?** The finite element `{x, y} ∈ |ℙD|` is the principal element of the
  generator `↓X ∪ ↓X'` (with `x = ↑X`, `y = ↑X'`); by `PFmap_rel_fin` its image under `ℙf` is
  generated by `↓(f x) ∪ ↓(f x')`, i.e. `ℙf({x, y}) = {f x, f x'}` — `ℙf` is the *image* operation.

Axiom audit: every declaration carries `Classical.choice`, but only at the `Prop` level and only
*inherited* from the power domain itself: `ℙ𝒟`'s closure under intersection (Proposition 7.10's
`PDmem_upSet_inter`) decides neighbourhood membership in an arbitrary system by `by_cases`, which is
genuinely undecidable at this generality. The new content of this file (the relation `PFmap`, the
display formula, both functor laws, and the r.e. reductions) adds **no further** use of choice; the
closure layer of `Recursive.lean` is choice-free, so `PFmap_isComputable*` add only the axioms of the
input `hf` on top of the power-domain's inherited `Classical.choice`.
-/

namespace Scott1980.Neighborhood

open NeighborhoodSystem Domain.Recursive ApproximableMap

variable {α β γ : Type*}

namespace NeighborhoodSystem

variable (V : NeighborhoodSystem α)

/-- **Every member of a `ℙ𝒟`-neighbourhood is a `𝒟`-neighbourhood.** -/
theorem PDmem_mem {A : Set (Set α)} (hA : V.PDmem A) {X : Set α} (hX : X ∈ A) : V.mem X := by
  obtain ⟨L, hL, rfl⟩ := hA
  obtain ⟨X', _, hXmem, _⟩ := (V.mem_PDunion).mp hX
  exact hXmem

/-- **`ℙ𝒟`-neighbourhoods are downward closed.** If `Z ∈ A` and `X ⊆ Z` with `X ∈ 𝒟`, then `X ∈ A`
(each `A = ⋃ ↓Xᵢ` is a union of down-sets). -/
theorem PDmem_down {A : Set (Set α)} (hA : V.PDmem A) {Z X : Set α}
    (hZ : Z ∈ A) (hXZ : X ⊆ Z) (hX : V.mem X) : X ∈ A := by
  obtain ⟨L, hL, rfl⟩ := hA
  obtain ⟨X', hX', _, hZsub⟩ := (V.mem_PDunion).mp hZ
  exact (V.mem_PDunion).mpr ⟨X', hX', hX, hXZ.trans hZsub⟩

end NeighborhoodSystem

variable {V : NeighborhoodSystem α} {W : NeighborhoodSystem β} {U : NeighborhoodSystem γ}

/-- **Exercise 7.19 (Scott 1981, PRG-19) — the functorial action `ℙf : ℙD → ℙE`.** Given an
approximable map `f : D → E`, the relation between `ℙD`- and `ℙE`-neighbourhoods is "every member of
the source is `f`-related to some member of the target". This is the representation-independent form
of Scott's displayed `∀ i < n ∃ j < m. Xᵢ f Yⱼ` (see `PFmap_rel_fin`). -/
def PFmap (f : ApproximableMap V W) : ApproximableMap V.PowerDomain W.PowerDomain where
  rel A B := V.PDmem A ∧ W.PDmem B ∧ ∀ X ∈ A, ∃ Y ∈ B, f.rel X Y
  rel_dom h := h.1
  rel_cod h := h.2.1
  master_rel := by
    refine ⟨V.PDmem_master, W.PDmem_master, ?_⟩
    rintro X ⟨hXmem, hXsub⟩
    exact ⟨W.master, ⟨W.master_mem, subset_rfl⟩,
      f.mono f.master_rel hXsub subset_rfl hXmem W.master_mem⟩
  inter_right := by
    rintro A B B' ⟨hA, hB, hbody⟩ ⟨-, hB', hbody'⟩
    refine ⟨hA, W.PDmem_inter hB hB', ?_⟩
    intro X hX
    obtain ⟨Y, hYB, hrel⟩ := hbody X hX
    obtain ⟨Y', hY'B', hrel'⟩ := hbody' X hX
    have hinmem : W.mem (Y ∩ Y') := f.rel_cod (f.inter_right hrel hrel')
    exact ⟨Y ∩ Y', Set.mem_inter
      (W.PDmem_down hB hYB Set.inter_subset_left hinmem)
      (W.PDmem_down hB' hY'B' Set.inter_subset_right hinmem),
      f.inter_right hrel hrel'⟩
  mono := by
    rintro A A' B B' ⟨_, _, hbody⟩ hA'A hBB' hA' hB'
    refine ⟨hA', hB', ?_⟩
    intro X hX
    obtain ⟨Y, hYB, hrel⟩ := hbody X (hA'A hX)
    exact ⟨Y, hBB' hYB, hrel⟩

@[simp] theorem PFmap_rel {f : ApproximableMap V W} {A : Set (Set α)} {B : Set (Set β)} :
    (PFmap f).rel A B ↔ V.PDmem A ∧ W.PDmem B ∧ ∀ X ∈ A, ∃ Y ∈ B, f.rel X Y := Iff.rfl

/-- **Exercise 7.19 — Scott's displayed formula.** On generators (finite lists of down-sets)
`(ℙf).rel (⋃_{X∈L₁} ↓X) (⋃_{Y∈L₂} ↓Y) ↔ ∀ X ∈ L₁, ∃ Y ∈ L₂, X f Y`, exactly Scott's
`∀ i < n ∃ j < m. Xᵢ f Yⱼ`. (`→` reads off the generators `Xᵢ`; `←` extends to all members by `mono`
and downward closure of the target.) -/
theorem PFmap_rel_fin (f : ApproximableMap V W) {L₁ : List (Set α)} {L₂ : List (Set β)}
    (hL₁ : ∀ X ∈ L₁, V.mem X) (hL₂ : ∀ Y ∈ L₂, W.mem Y) :
    (PFmap f).rel (⋃ X ∈ L₁, V.upSet X) (⋃ Y ∈ L₂, W.upSet Y)
      ↔ ∀ X ∈ L₁, ∃ Y ∈ L₂, f.rel X Y := by
  constructor
  · rintro ⟨-, -, hbody⟩ X hX
    have hXin : X ∈ ⋃ X' ∈ L₁, V.upSet X' :=
      (V.mem_PDunion).mpr ⟨X, hX, hL₁ X hX, subset_rfl⟩
    obtain ⟨Z, hZin, hrel⟩ := hbody X hXin
    obtain ⟨Y, hY, hZmem, hZsub⟩ := (W.mem_PDunion).mp hZin
    exact ⟨Y, hY, f.mono hrel subset_rfl hZsub (hL₁ X hX) (hL₂ Y hY)⟩
  · intro hgen
    refine ⟨⟨L₁, hL₁, rfl⟩, ⟨L₂, hL₂, rfl⟩, ?_⟩
    rintro Z hZin
    obtain ⟨X, hX, hZmem, hZsub⟩ := (V.mem_PDunion).mp hZin
    obtain ⟨Y, hY, hrel⟩ := hgen X hX
    exact ⟨Y, (W.mem_PDunion).mpr ⟨Y, hY, hL₂ Y hY, subset_rfl⟩,
      f.mono hrel hZsub subset_rfl hZmem (hL₂ Y hY)⟩

/-! ### Functoriality: `ℙ` preserves identities and composition. -/

/-- **Exercise 7.19 — `ℙ` preserves identity maps.** `ℙ(I_D) = I_{ℙD}`. The body
`∀ X ∈ A, ∃ Y ∈ B, X ⊆ Y` is equivalent to `A ⊆ B` by downward closure of `B`. -/
theorem PFmap_idMap (V : NeighborhoodSystem α) : PFmap (idMap V) = idMap V.PowerDomain := by
  apply ApproximableMap.ext
  intro A B
  simp only [PFmap_rel, idMap_rel, PowerDomain_mem]
  constructor
  · rintro ⟨hA, hB, hbody⟩
    refine ⟨hA, hB, ?_⟩
    intro X hX
    obtain ⟨Y, hYB, hXmem, _, hXY⟩ := hbody X hX
    exact V.PDmem_down hB hYB hXY hXmem
  · rintro ⟨hA, hB, hsub⟩
    refine ⟨hA, hB, ?_⟩
    intro X hX
    exact ⟨X, hsub hX, V.PDmem_mem hA hX, V.PDmem_mem hA hX, subset_rfl⟩

/-- Choice-free gathering of composition witnesses along the generators of the source: from a list
`L` of `𝒟`-neighbourhoods each admitting a `(g∘f)`-witness into `C`, build a single list `M` of
`ℰ`-neighbourhoods covering every `X ∈ L` from the `f`-side and covered into `C` from the `g`-side.
Proved by list recursion `obtain`-ing the witnesses (no choice in a `Prop` goal). -/
theorem comp_witness (f : ApproximableMap V W) (g : ApproximableMap W U) (C : Set (Set γ)) :
    ∀ (L : List (Set α)), (∀ X ∈ L, V.mem X) →
      (∀ X ∈ L, ∃ Z, Z ∈ C ∧ ∃ Y, f.rel X Y ∧ g.rel Y Z) →
      ∃ M : List (Set β), (∀ Y ∈ M, W.mem Y) ∧
        (∀ X ∈ L, ∃ Y ∈ M, f.rel X Y) ∧ (∀ Y ∈ M, ∃ Z ∈ C, g.rel Y Z) := by
  intro L
  induction L with
  | nil =>
    intro _ _
    refine ⟨[], ?_, ?_, ?_⟩
    · intro Y hY; cases hY
    · intro X hX; cases hX
    · intro Y hY; cases hY
  | cons X L ih =>
    intro hL hpre
    obtain ⟨Zx, hZxC, Yx, hfx, hgx⟩ := hpre X (List.mem_cons.mpr (Or.inl rfl))
    obtain ⟨M, hMmem, hfM, hgM⟩ :=
      ih (fun X' hX' => hL X' (List.mem_cons.mpr (Or.inr hX')))
         (fun X' hX' => hpre X' (List.mem_cons.mpr (Or.inr hX')))
    refine ⟨Yx :: M, ?_, ?_, ?_⟩
    · intro Y hY
      rcases List.mem_cons.mp hY with rfl | hY'
      · exact f.rel_cod hfx
      · exact hMmem Y hY'
    · intro X' hX'
      rcases List.mem_cons.mp hX' with rfl | hX''
      · exact ⟨Yx, List.mem_cons.mpr (Or.inl rfl), hfx⟩
      · obtain ⟨Y, hYM, hrel⟩ := hfM X' hX''
        exact ⟨Y, List.mem_cons.mpr (Or.inr hYM), hrel⟩
    · intro Y hY
      rcases List.mem_cons.mp hY with rfl | hY'
      · exact ⟨Zx, hZxC, hgx⟩
      · exact hgM Y hY'

/-- **Exercise 7.19 — `ℙ` preserves composition.** `ℙ(g ∘ f) = ℙg ∘ ℙf`. The forward direction
constructs the intermediate `ℙE`-neighbourhood from `comp_witness`; the backward direction merely
threads the existential witnesses. -/
theorem PFmap_comp (g : ApproximableMap W U) (f : ApproximableMap V W) :
    PFmap (g.comp f) = (PFmap g).comp (PFmap f) := by
  apply ApproximableMap.ext
  intro A C
  simp only [PFmap_rel, comp_rel]
  constructor
  · rintro ⟨hA, hC, hbody⟩
    obtain ⟨L, hL, rfl⟩ := hA
    have hpre : ∀ X ∈ L, ∃ Z, Z ∈ C ∧ ∃ Y, f.rel X Y ∧ g.rel Y Z := by
      intro X hX
      obtain ⟨Z, hZC, Y, hfXY, hgYZ⟩ :=
        hbody X ((V.mem_PDunion).mpr ⟨X, hX, hL X hX, subset_rfl⟩)
      exact ⟨Z, hZC, Y, hfXY, hgYZ⟩
    obtain ⟨M, hMmem, hfL, hgM⟩ := comp_witness f g C L hL hpre
    refine ⟨⋃ Y ∈ M, W.upSet Y,
      ⟨⟨L, hL, rfl⟩, ⟨M, hMmem, rfl⟩, ?_⟩, ⟨M, hMmem, rfl⟩, hC, ?_⟩
    · intro X hX
      obtain ⟨X', hX', hXmem, hXsub⟩ := (V.mem_PDunion).mp hX
      obtain ⟨Y, hYM, hrel⟩ := hfL X' hX'
      exact ⟨Y, (W.mem_PDunion).mpr ⟨Y, hYM, hMmem Y hYM, subset_rfl⟩,
        f.mono hrel hXsub subset_rfl hXmem (hMmem Y hYM)⟩
    · intro Y hY
      obtain ⟨Y', hY', hYmem, hYsub⟩ := (W.mem_PDunion).mp hY
      obtain ⟨Z, hZC, hrel⟩ := hgM Y' hY'
      exact ⟨Z, hZC, g.mono hrel hYsub subset_rfl hYmem (g.rel_cod hrel)⟩
  · rintro ⟨B, ⟨hA, hB, hfAB⟩, _, hC, hgBC⟩
    refine ⟨hA, hC, ?_⟩
    intro X hX
    obtain ⟨Y, hYB, hfXY⟩ := hfAB X hX
    obtain ⟨Z, hZC, hgYZ⟩ := hgBC Y hYB
    exact ⟨Z, hZC, Y, hfXY, hgYZ⟩

/-! ### Computability: if `f` is computable then so is `ℙf` (Scott's first question). -/

/-- **Bounded `∃` over a coded list preserves recursive enumerability.** If `R` is r.e. then so is
`fun d a => ∃ b ∈ decodeList d, R a b`: project out `b` (`REPred.proj`) over the conjunction of the
*recursively decidable* membership `b ∈ decodeList d` with the r.e. body `R a b`. -/
theorem bExists_decodeList_re {R : ℕ → ℕ → Prop} (hR : REPred₂ R) :
    REPred₂ (fun d a => ∃ b ∈ decodeList d, R a b) := by
  have hmem : RecDecidable₂ (fun d b => b ∈ decodeList d) := by
    have heq : RecDecidable₂ (fun e b => e = b) :=
      RecDecidable.natEq Nat.Primrec.left Nat.Primrec.right
    have hbase : RecDecidable₂ (fun d b => ∃ e ∈ decodeList d, e = b) := heq.bExistsList
    refine RecDecidable.of_iff (fun t => ?_) hbase
    constructor
    · intro h; exact ⟨_, h, rfl⟩
    · rintro ⟨e, he, rfl⟩; exact he
  have hpart1 : REPred (fun w : ℕ => w.unpair.1 ∈ decodeList w.unpair.2.unpair.1) := by
    have hg : Nat.Primrec (fun w : ℕ => Nat.pair w.unpair.2.unpair.1 w.unpair.1) :=
      (Nat.Primrec.left.comp Nat.Primrec.right).pair Nat.Primrec.left
    refine RecDecidable.re (RecDecidable.of_iff (fun w => ?_) (hmem.comp hg))
    simp only [unpair_pair_fst, unpair_pair_snd]
  have hpart2 : REPred (fun w : ℕ => R w.unpair.2.unpair.2 w.unpair.1) := by
    have hg : Nat.Primrec (fun w : ℕ => Nat.pair w.unpair.2.unpair.2 w.unpair.1) :=
      (Nat.Primrec.right.comp Nat.Primrec.right).pair Nat.Primrec.left
    refine REPred.of_iff (fun w => ?_) (REPred.comp hR hg)
    simp only [unpair_pair_fst, unpair_pair_snd]
  refine REPred.of_iff (fun s => ?_) (hpart1.and hpart2).proj
  simp only [unpair_pair_fst, unpair_pair_snd]

/-- **Exercise 7.19 — the relation of `ℙf` at the level of `ℙ𝒟`-codes.** Over the canonical
presentations of Proposition 7.10, `(ℙf).rel (Y_c) (Y_d) ↔ ∀ a ∈ dl c, ∃ b ∈ dl d, Xₐ f Y_b`. -/
theorem PFmap_rel_Ypd_iff (P : ComputablePresentation V) (Q : ComputablePresentation W)
    (f : ApproximableMap V W) {c d : ℕ} :
    (PFmap f).rel (V.Ypd P c) (W.Ypd Q d) ↔
      ∀ a ∈ decodeList c, ∃ b ∈ decodeList d, f.rel (P.X a) (Q.X b) := by
  constructor
  · rintro ⟨-, -, hbody⟩ a ha
    have hXin : P.X a ∈ V.Ypd P c := (V.mem_Ypd P).mpr ⟨a, ha, P.mem_X a, subset_rfl⟩
    obtain ⟨Y, hYin, hrel⟩ := hbody (P.X a) hXin
    obtain ⟨b, hb, hYmem, hYsub⟩ := (W.mem_Ypd Q).mp hYin
    exact ⟨b, hb, f.mono hrel subset_rfl hYsub (P.mem_X a) (Q.mem_X b)⟩
  · intro hgen
    refine ⟨V.Ypd_isPDmem P c, W.Ypd_isPDmem Q d, ?_⟩
    rintro X hXin
    obtain ⟨a, ha, hXmem, hXsub⟩ := (V.mem_Ypd P).mp hXin
    obtain ⟨b, hb, hrel⟩ := hgen a ha
    exact ⟨Q.X b, (W.mem_Ypd Q).mpr ⟨b, hb, Q.mem_X b, subset_rfl⟩,
      f.mono hrel hXsub subset_rfl hXmem (Q.mem_X b)⟩

/-- **Exercise 7.19 (Scott's first question) — `ℙf` is computable when `f` is.** Stated at the level
of the `ℙ𝒟`-codes of Proposition 7.10 (`Y_c = ⋃_{a∈dl c} ↓Xₐ`): the relation `(ℙf).rel (Y_c) (Y_d)`
is recursively enumerable in `(c, d)`. -/
theorem PFmap_isComputable_Ypd (P : ComputablePresentation V) (Q : ComputablePresentation W)
    {f : ApproximableMap V W} (hf : IsComputableMap P Q f) :
    REPred₂ (fun c d => (PFmap f).rel (V.Ypd P c) (W.Ypd Q d)) := by
  have hR : REPred₂ (fun a b => f.rel (P.X a) (Q.X b)) := hf
  have hInner : REPred₂ (fun d a => ∃ b ∈ decodeList d, f.rel (P.X a) (Q.X b)) :=
    bExists_decodeList_re hR
  have hForall := REPred.forall_mem_decodeList₂ hInner
  have hswap : Nat.Primrec (fun s : ℕ => Nat.pair s.unpair.2 s.unpair.1) :=
    Nat.Primrec.right.pair Nat.Primrec.left
  refine REPred.of_iff (fun s => ?_) (hForall.comp hswap)
  simp only [unpair_pair_fst, unpair_pair_snd]
  exact PFmap_rel_Ypd_iff P Q f

/-- **Exercise 7.19 (Scott's first question), packaged.** `ℙf` is a computable map between the
canonical effective presentations `ℙ𝒟`, `ℙℰ` (Proposition 7.10) whenever `f` is computable. -/
theorem PFmap_isComputable (P : ComputablePresentation V) (Q : ComputablePresentation W)
    (consV : ℕ → ℕ) (hconsVp : Nat.Primrec consV)
    (hconsVs : ∀ a b, consV (Nat.pair a b) = 1 ↔ ∃ k, P.X k ⊆ P.X a ∩ P.X b)
    (consW : ℕ → ℕ) (hconsWp : Nat.Primrec consW)
    (hconsWs : ∀ a b, consW (Nat.pair a b) = 1 ↔ ∃ k, Q.X k ⊆ Q.X a ∩ Q.X b)
    {f : ApproximableMap V W} (hf : IsComputableMap P Q f) :
    IsComputableMap (V.PDPresentation P consV hconsVp hconsVs)
      (W.PDPresentation Q consW hconsWp hconsWs) (PFmap f) := by
  exact PFmap_isComputable_Ypd P Q hf

end Scott1980.Neighborhood
